/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "sanctum.csrf-cookie": [],
    "api.workspace": [],
    "api.tasks.bulk": [],
    "api.tasks.reorder": [],
    "api.tasks.export": [],
    "api.tasks.restore": [
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "api.trash.tasks.destroy": [],
    "api.tasks.index": [],
    "api.tasks.store": [],
    "api.tasks.show": [
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "api.tasks.update": [
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "api.tasks.destroy": [
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "api.categories.index": [],
    "api.categories.store": [],
    "api.categories.show": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "api.categories.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "api.categories.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "api.tasks.subtasks.index": [
        {
            "name": "task",
            "required": true
        }
    ],
    "api.tasks.subtasks.store": [
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "api.subtasks.show": [
        {
            "name": "subtask",
            "required": true
        }
    ],
    "api.subtasks.update": [
        {
            "name": "subtask",
            "required": true,
            "binding": "id"
        }
    ],
    "api.subtasks.destroy": [
        {
            "name": "subtask",
            "required": true,
            "binding": "id"
        }
    ],
    "api.subtasks.toggle": [
        {
            "name": "subtask",
            "required": true,
            "binding": "id"
        }
    ],
    "api.reminders.store": [],
    "api.reminders.destroy": [
        {
            "name": "reminder",
            "required": true,
            "binding": "id"
        }
    ],
    "home": [],
    "tasks.index": [],
    "settings.index": [],
    "api.data.export": [],
    "api.data.import": [],
    "api.data.destroy-all": [],
    "api.lists.reorder": [],
    "api.todos.bulk": [],
    "api.todos.reorder": [],
    "api.todos.restore": [
        {
            "name": "todo",
            "required": true,
            "binding": "id"
        }
    ],
    "api.todos.permanent": [
        {
            "name": "todo",
            "required": true,
            "binding": "id"
        }
    ],
    "api.todos.trash.empty": [],
    "api.lists.index": [],
    "api.lists.store": [],
    "api.lists.show": [
        {
            "name": "list",
            "required": true,
            "binding": "id"
        }
    ],
    "api.lists.update": [
        {
            "name": "list",
            "required": true,
            "binding": "id"
        }
    ],
    "api.lists.destroy": [
        {
            "name": "list",
            "required": true,
            "binding": "id"
        }
    ],
    "api.todos.index": [],
    "api.todos.store": [],
    "api.todos.show": [
        {
            "name": "todo",
            "required": true,
            "binding": "id"
        }
    ],
    "api.todos.update": [
        {
            "name": "todo",
            "required": true,
            "binding": "id"
        }
    ],
    "api.todos.destroy": [
        {
            "name": "todo",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
